apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  labels:
    app: kafka-manager
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
    #nodePort: 30029
  selector:
    app: kafka-manager
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  labels:
    app: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: rkazak1/kafka-manager:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ZK_HOSTS
          value: zk-svc.test:2181
        command:
        - ./bin/kafka-manager
        - -Dhttp.port=80
